// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appspot.cloudserviceapi;

import com.appspot.cloudserviceapi.Service;

privileged aspect Service_Roo_JavaBean {
    
    public String Service.getService() {
        return this.service;
    }
    
    public void Service.setService(String service) {
        this.service = service;
    }
    
}
