/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.appspot.cloudserviceapi.dao.gae;


import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;

import com.appspot.cloudserviceapi.dao.*;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    public GeniuDao createGeniuDao( DatastoreService ds ) {
        return new GeniuDaoImpl( ds );
    }

	public HumaDao createHumaDao(DatastoreService ds) {
        return new HumaDaoImpl( ds );
	}

	public SecureDao createSecureDao(DatastoreService ds) {
        return new SecureDaoImpl( ds );
	}
}
