/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.appspot.cloudserviceapi.dao.gae;


import java.sql.Date;
import java.util.ArrayList;

import com.appspot.cloudserviceapi.dao.HumaDao;
import com.appspot.cloudserviceapi.dto.Huma;
import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.KeyFactory;
import com.google.appengine.api.datastore.Query;
import com.google.appengine.api.datastore.Text;
import com.spoledge.audao.db.dao.DaoException;
import com.spoledge.audao.db.dao.gae.GaeAbstractDaoImpl;


/**
 * This is the DAO imlementation class.
 *
 * @author generated
 */
public class HumaDaoImpl extends GaeAbstractDaoImpl<Huma> implements HumaDao {

    private static final String TABLE_NAME = "Huma";

    public HumaDaoImpl( DatastoreService ds ) {
        super( ds );
    }

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public Huma findByPrimaryKey( long id ) {
        Entity _ent = entityGet( new KeyFactory.Builder( "Huma", id ).getKey());

        return _ent != null ? fetch( null, _ent ) : null;
    }

    /**
     * Finds a record.
     */
    public Huma findByWhat( String what ) {
        Query _query = getQuery();
        _query.addFilter( "what", Query.FilterOperator.EQUAL, what );

        return findOne( _query, "what = :1", 0, what);
    }

    /**
     * Finds records ordered by what.
     */
    public Huma[] findAll( ) {
        Query _query = getQuery();

        multipleQueries = false;
        String _cond = "1 = 1";

        return findManyArray( _query, _cond, 0, -1 );
    }

    /**
     * Deletes a record identified by its primary key.
     * @return true iff the record was really deleted (existed)
     */
    public boolean deleteByPrimaryKey( long id ) throws DaoException {
        return entityDelete( new KeyFactory.Builder( "Huma", id ).getKey() );
    }

    /**
     * Inserts a new record.
     * @return the generated primary key - id
     */
    public long insert( Huma dto ) throws DaoException {
        Entity _ent = new Entity( "Huma");

        {
            if ( dto.getPlatform() == null ) {
                throw new DaoException("Value of column 'platform' cannot be null");
            }
            checkMaxLength( "platform", dto.getPlatform(), 500 );
            _ent.setProperty( "platform", dto.getPlatform());

            if ( dto.getWhat() == null ) {
                throw new DaoException("Value of column 'what' cannot be null");
            }
            checkMaxLength( "what", dto.getWhat(), 500 );
            _ent.setProperty( "what", dto.getWhat());

            if ( dto.getDetails() == null ) {
                throw new DaoException("Value of column 'details' cannot be null");
            }
            checkMaxLength( "details", dto.getDetails(), 10000 );
            _ent.setProperty( "details", new Text( dto.getDetails() ));

            if ( dto.getSimilarity() == null ) {
                throw new DaoException("Value of column 'similarity' cannot be null");
            }
            checkMaxLength( "similarity", dto.getSimilarity(), 500 );
            _ent.setProperty( "similarity", dto.getSimilarity());

            if ( dto.getCreatedDate() == null ) {
                dto.setCreatedDate( new Date( System.currentTimeMillis()));
            }
//            _ent.setProperty( "createdDate", date( dto.getCreatedDate() ));

            if ( dto.getLastUpdatedDate() == null ) {
                dto.setLastUpdatedDate( new Date( System.currentTimeMillis()));
            }
//            _ent.setProperty( "lastUpdatedDate", date( dto.getLastUpdatedDate() ));

            if ( dto.getLastAccessedDate() == null ) {
                dto.setLastAccessedDate( new Date( System.currentTimeMillis()));
            }
//            _ent.setProperty( "lastAccessedDate", date( dto.getLastAccessedDate() ));
        }

        entityPut( _ent, dto, "insert" );

        dto.setId( _ent.getKey().getId());

        return dto.getId();
    }

    /**
     * Updates one record found by primary key.
     * @return true iff the record was really updated (=found and any change was really saved)
     */
    public boolean update( long id, Huma dto ) throws DaoException {
        Entity _ent = entityGet( new KeyFactory.Builder( "Huma", id ).getKey());
        if (_ent == null) return false;

        boolean isUpdated = false;

        if ( dto.getId() != null ) {
            isUpdated = true;
        }

        if ( dto.getPlatform() != null ) {
            checkMaxLength( "platform", dto.getPlatform(), 500 );
            _ent.setProperty( "platform", dto.getPlatform());
            isUpdated = true;
        }

        if ( dto.getWhat() != null ) {
            checkMaxLength( "what", dto.getWhat(), 500 );
            _ent.setProperty( "what", dto.getWhat());
            isUpdated = true;
        }

        if ( dto.getDetails() != null ) {
            checkMaxLength( "details", dto.getDetails(), 10000 );
            _ent.setProperty( "details", new Text( dto.getDetails() ));
            isUpdated = true;
        }

        if ( dto.getSimilarity() != null ) {
            checkMaxLength( "similarity", dto.getSimilarity(), 500 );
            _ent.setProperty( "similarity", dto.getSimilarity());
            isUpdated = true;
        }

        if ( dto.getCreatedDate() != null ) {
//            _ent.setProperty( "createdDate", date( dto.getCreatedDate() ));
            isUpdated = true;
        }

        if ( dto.getLastUpdatedDate() != null ) {
//            _ent.setProperty( "lastUpdatedDate", date( dto.getLastUpdatedDate() ));
            isUpdated = true;
        }

        if ( dto.getLastAccessedDate() != null ) {
//            _ent.setProperty( "lastAccessedDate", date( dto.getLastAccessedDate() ));
            isUpdated = true;
        }

        if (!isUpdated) {
            return false;
        }

        entityPut( _ent, dto, "update" );

        return true;
    }

    /**
     * Returns the table name.
     */
    public String getTableName() {
        return TABLE_NAME;
    }

    protected Huma fetch( Huma dto, Entity ent ) {
        if ( dto == null ) dto = new Huma();

        dto.setId( ent.getKey().getId());
        dto.setPlatform( getString( ent, "platform" ));
        dto.setWhat( getString( ent, "what" ));
        dto.setDetails( getString( ent, "details" ));
        dto.setSimilarity( getString( ent, "similarity" ));
        dto.setCreatedDate( getDate( ent, "createdDate" ));
        dto.setLastUpdatedDate( getDate( ent, "lastUpdatedDate" ));
        dto.setLastAccessedDate( getDate( ent, "lastAccessedDate" ));

        return dto;
    }

    protected Huma[] toArray(ArrayList<Huma> list ) {
        Huma[] ret = new Huma[ list.size() ];
        return list.toArray( ret );
    }

}
