/**
  *CrudServiceLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 01/18/2016
  */


angular.module('CrudServiceLib').factory('ActionEnum', function() {
    return {
   
     //TODO: Write general description for this element
    
    CREATE : "create",

   
     //TODO: Write general description for this element
    
    UPDATE : "update",

   
     //TODO: Write general description for this element
    
    DELETE : "delete",

   
     //TODO: Write general description for this element
    
    MIGRATE : "migrate",

   
     //TODO: Write general description for this element
    
    MIGRATE_DELETE : "migrate_delete",

   
     //TODO: Write general description for this element
    
    PURGECALENDAR : "purgecalendar",

   
     //TODO: Write general description for this element
    
    SCHEDULED : "scheduled",

   
     //TODO: Write general description for this element
    
    SHARED : "shared",

    };
});