/**
  *CrudServiceLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 01/18/2016
  */


angular.module('CrudServiceLib').factory('Action13Enum', function() {
    return {
   
     //TODO: Write general description for this element
    
    CREATE : "create",

   
     //TODO: Write general description for this element
    
    UPDATE : "update",

   
     //TODO: Write general description for this element
    
    DELETE : "delete",

    };
});