/**
  *CrudServiceLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 01/18/2016
  */


angular.module('CrudServiceLib').factory('FilterEnum', function() {
    return {
   
     //TODO: Write general description for this element
    
    NEXT5 : "next5",

   
     //TODO: Write general description for this element
    
    OWNEDBYME : "ownedbyme",

   
     //TODO: Write general description for this element
    
    SCHEDULED : "scheduled",

   
     //TODO: Write general description for this element
    
    SHARED : "shared",

    };
});