/**
  *CrudServiceLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 01/18/2016
  */


angular.module('CrudServiceLib').factory('TypeEnum', function() {
    return {
   
     //TODO: Write general description for this element
    
    MODELCALENDAR : "modelCalendar",

   
     //TODO: Write general description for this element
    
    MODELMOVIE : "modelMovie",

   
     //TODO: Write general description for this element
    
    MODELUSER : "modelUser",

    };
});