/**
 *ServiceManagerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 12/18/2015
 */

'use strict';
angular.module('ServiceManagerLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        //BASEURI : "http://chudoon3t.appspot.com"
        BASEURI : "http://localhost:8888"
    };
});

