/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.ypg.db.dao.gae;


import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;

import com.ypg.db.dao.*;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    public PartnerDao createPartnerDao( DatastoreService ds ) {
        return new PartnerDaoImpl( ds );
    }

    public BusinesDao createBusinesDao( DatastoreService ds ) {
        return new BusinesDaoImpl( ds );
    }

}
