<%@page contentType="text/html;charset=UTF-8" language="java" %>
<%@page import="tapp.model.sgc.WorkOrder" %>
<%@page import="com.appspot.cloudserviceapi.common.StringUtil" %>
<%@page import="com.appspot.cloudserviceapi.common.Constants" %>

<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Payment Request Form</title>
  </head>

  <body>
<!--	You are logged in as <%= request.getAttribute("userID") %> and update will be logged under this account.
-->
<!--  begin - generated by jot form -->
<!-- replace action="http://www.jotform.com/submit.php" with 
action="/sgc/work"
-->

<jsp:include page="../html/pc/payment-form.html"/>

<!--  end - generated by jot form -->

  </body>
</html>
