package com.appspot.cloudserviceapi.eo.test;

public enum ActivityDetails {

	ONE_HOUR_A_WEEK,
	TWO_ONE_HOUR_SESSIONS_A_WEEK,
	FOUR_30_MINUTES_SESSIONS_A_WEEK,
	THREE_HOURS_A_WEEK,
	FOUR_ONE_HOUR_SESSIONS_A_WEEK,
	EIGHT_30_MINUTES_SESSIONS_A_WEEK,
	FIVE_TIMES_A_WEEK

}
