/**
 *CrudServiceLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/18/2016
 */

'use strict';
angular.module('CrudServiceLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "http://example.com/api"

    };
});

