package com.appspot.cloudserviceapi.security.spring;

public enum UserRole {

	ROLE_USER, ROLE_MANAGER, ROLE_ADMIN, 
	ROLE_USER_SCI, ROLE_MANAGER_SCI, ROLE_ADMIN_SCI,
	ROLE_USER_EO, ROLE_MANAGER_EO, ROLE_ADMIN_EO,
	ROLE_USER_CODESION, ROLE_MANAGER_CODESION, ROLE_ADMIN_CODESION,
	ROLE_USER_XMM, 
	ROLE_ADMIN_GU, ROLE_BUSINESS_OWNER_GU, ROLE_MEMBER_GU, ROLE_PARTNER_GU, ROLE_CASHIER_GU

}
