/**
  *ServiceManagerLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 12/18/2015
  */


angular.module('ServiceManagerLib').factory('Action14Enum', function() {
    return {
   
     //TODO: Write general description for this element
    
    CREATE : "create",

   
     //TODO: Write general description for this element
    
    UPDATE : "update",

   
     //TODO: Write general description for this element
    
    DELETE : "delete",

    };
});