/**
  *ServiceManagerLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 12/18/2015
  */


angular.module('ServiceManagerLib').factory('CategoryEnum', function() {
    return {
   
     //TODO: Write general description for this element
    
    TECHNOLOGY : "TECHNOLOGY",

   
     //TODO: Write general description for this element
    
    RELATIONSHIP : "RELATIONSHIP",

   
     //TODO: Write general description for this element
    
    INCOMING : "INCOMING",

   
     //TODO: Write general description for this element
    
    OUTGOING : "OUTGOING",

   
     //TODO: Write general description for this element
    
    SCIENCE : "SCIENCE",

   
     //TODO: Write general description for this element
    
    BUSINESS : "BUSINESS",

   
     //TODO: Write general description for this element
    
    WORLD : "WORLD",

   
     //TODO: Write general description for this element
    
    SPORTS : "SPORTS",

   
     //TODO: Write general description for this element
    
    ENTERTAINMENT : "ENTERTAINMENT",

   
     //TODO: Write general description for this element
    
    HEALTH : "HEALTH",

   
     //TODO: Write general description for this element
    
    POLITICS : "POLITICS",

   
     //TODO: Write general description for this element
    
    SOCIETY : "SOCIETY",

   
     //TODO: Write general description for this element
    
    GOVERNMENT : "GOVERNMENT",

   
     //TODO: Write general description for this element
    
    CODE : "CODE",

   
     //TODO: Write general description for this element
    
    AUDIO : "AUDIO",

   
     //TODO: Write general description for this element
    
    VIDEO : "VIDEO",

   
     //TODO: Write general description for this element
    
    IMAGE : "IMAGE",

   
     //TODO: Write general description for this element
    
    GAME : "GAME",

    };
});