/**
  *ServiceManagerLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 12/18/2015
  */


angular.module('ServiceManagerLib').factory('TypeEnum', function() {
    return {
   
     //TODO: Write general description for this element
    
    MODELCALENDAR : "modelCalendar",

   
     //TODO: Write general description for this element
    
    MODELMOVIE : "modelMovie",

   
     //TODO: Write general description for this element
    
    MODELUSER : "modelUser",

    };
});