<? 
include('config.php'); 
echo "<table border=1 >"; 
echo "<tr>"; 
echo "<td><b>Id</b></td>"; 
echo "<td><b>DatePerformed</b></td>"; 
echo "<td><b>DateRequested</b></td>"; 
echo "<td><b>Address1</b></td>"; 
echo "<td><b>Address2</b></td>"; 
echo "<td><b>AddtionalService1</b></td>"; 
echo "<td><b>AddtionalService2</b></td>"; 
echo "<td><b>AddtionalService3</b></td>"; 
echo "<td><b>AddtionalService4</b></td>"; 
echo "<td><b>AddtionalService5</b></td>"; 
echo "<td><b>AddtionalServiceComments</b></td>"; 
echo "<td><b>AllergicInfo</b></td>"; 
echo "<td><b>ChildrenInfo</b></td>"; 
echo "<td><b>City</b></td>"; 
echo "<td><b>Country</b></td>"; 
echo "<td><b>Email</b></td>"; 
echo "<td><b>FirstName</b></td>"; 
echo "<td><b>LastName</b></td>"; 
echo "<td><b>PetComments</b></td>"; 
echo "<td><b>PetInfo</b></td>"; 
echo "<td><b>Phone</b></td>"; 
echo "<td><b>Postal</b></td>"; 
echo "<td><b>PrimaryCleaningComments</b></td>"; 
echo "<td><b>PrimaryCleaningReason</b></td>"; 
echo "<td><b>ResidenceType</b></td>"; 
echo "<td><b>Room1Info</b></td>"; 
echo "<td><b>Room2Info</b></td>"; 
echo "<td><b>Room3Info</b></td>"; 
echo "<td><b>SpecialInstruction</b></td>"; 
echo "<td><b>State</b></td>"; 
echo "<td><b>Title</b></td>"; 
echo "<td><b>Allergic</b></td>"; 
echo "<td><b>HasPet</b></td>"; 
echo "<td><b>AlternatePhone</b></td>"; 
echo "<td><b>BathRoom</b></td>"; 
echo "<td><b>BedRoom</b></td>"; 
echo "<td><b>Children</b></td>"; 
echo "<td><b>FamilySize</b></td>"; 
echo "<td><b>HoursSpent</b></td>"; 
echo "</tr>"; 
$result = mysql_query("SELECT * FROM `workorder`") or trigger_error(mysql_error()); 
while($row = mysql_fetch_array($result)){ 
foreach($row AS $key => $value) { $row[$key] = stripslashes($value); } 
echo "<tr>";  
echo "<td valign='top'>" . nl2br( $row['id']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['datePerformed']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['dateRequested']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['address1']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['address2']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['addtionalService1']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['addtionalService2']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['addtionalService3']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['addtionalService4']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['addtionalService5']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['addtionalServiceComments']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['allergicInfo']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['childrenInfo']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['city']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['country']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['email']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['firstName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['lastName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['petComments']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['petInfo']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['phone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['postal']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['primaryCleaningComments']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['primaryCleaningReason']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['residenceType']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['room1Info']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['room2Info']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['room3Info']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['specialInstruction']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['state']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['title']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['allergic']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['hasPet']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['alternatePhone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['bathRoom']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['bedRoom']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['children']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['familySize']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['hoursSpent']) . "</td>";  
echo "<td valign='top'><a href=edit.php?id={$row['id']}>Edit</a></td><td><a href=delete.php?id={$row['id']}>Delete</a></td> "; 
echo "</tr>"; 
} 
echo "</table>"; 
echo "<a href=new.php>New Row</a>"; 
?>